### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by anderslemke** [RailsEventStore/rails_event_store#533]
I'm currently working on PR #529 but I'm having tests that fails locally on the master branch.

Any help would be appreciated.

Here are some examples:

In `ruby_event_store` I get this:

```

  5) RubyEventStore::Mappers::Protobuf #serialized_record_to_event is using events class remapping
     Failure/Error: raise LoadError, "cannot load such file -- protobuf_nested_struct. Add protobuf_nested_struct gem to Gemfile"

     LoadError:
       cannot load such file -- protobuf_nested_struct. Add protobuf_nested_struct gem to Gemfile
     # ./lib/ruby_event_store/mappers/protobuf.rb:62:in `rescue in require_optional_dependency'
     # ./lib/ruby_event_store/mappers/protobuf.rb:60:in `require_optional_dependency'
     # ./lib/ruby_event_store/mappers/protobuf.rb:17:in `initialize'
     # ./spec/mappers/protobuf_spec.rb:218:in `new'
     # ./spec/mappers/protobuf_spec.rb:218:in `block (2 levels) in <module:Mappers>'
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # LoadError:
     #   cannot load such file -- google/protobuf/any_pb
     #   ./lib/ruby_event_store/mappers/protobuf.rb:60:in `require'

Finished in 2.88 seconds (files took 0.6519 seconds to load)
600 examples, 5 failures, 7 pending

Failed examples:

rspec ./spec/mappers/protobuf_spec.rb:244 # RubyEventStore::Mappers::Protobuf #event_to_serialized_record raises error when wrong data
rspec ./spec/mappers/protobuf_spec.rb:199 # RubyEventStore::Mappers::Protobuf #event_to_serialized_record returns proto serialized record
rspec ./spec/mappers/protobuf_spec.rb:232 # RubyEventStore::Mappers::Protobuf #event_to_serialized_record raises error when no data
rspec ./spec/mappers/protobuf_spec.rb:208 # RubyEventStore::Mappers::Protobuf #serialized_record_to_event returns event instance
rspec ./spec/mappers/protobuf_spec.rb:217 # RubyEventStore::Mappers::Protobuf #serialized_record_to_event is using events class remapping
```

In `rails_event_story_active_record` I'm seeing this:

```
Failures:

  1) database schema migrations migrate from v0.33.0 to v0.34.0
     Failure/Error:
       validate_migration('Gemfile.0_33_0', 'Gemfile.0_34_0',
                          source_template_name: 'migration') do
         run_migration('index_by_event_type')
         run_migration('limit_for_event_id')
       end

       expected: 0
            got: 7

       (compared using ==)
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/subprocess_helper.rb:23:in `run_subprocess'
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/subprocess_helper.rb:30:in `block in run_in_subprocess'
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/subprocess_helper.rb:27:in `run_in_subprocess'
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/schema_helper.rb:44:in `build_schema'
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/schema_helper.rb:81:in `validate_migration'
     # ./spec/migrations_spec.rb:8:in `block (2 levels) in <top (required)>'
     # /Users/anders/Projects/anderslemke/rails_event_store/lib/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'

Finished in 12.56 seconds (files took 0.95627 seconds to load)
99 examples, 1 failure, 6 pending

Failed examples:

rspec ./spec/migrations_spec.rb:7 # database schema migrations migrate from v0.33.0 to v0.34.0

Randomized with seed 62343

make: *** [test] Error 1
```

In `ruby_event_store-rom` I get a lot of these:

```
  130) RubyEventStore::ROM::EventRepository behaves like rom_event_repository behaves like event_repository #update_messages changes events
       Failure/Error:
         relation.by_pk(to_a.map { |e| e[:id] }).each do |tuple|
           raise TupleUniquenessError.for_event_id(tuple[:id])
         end

       SystemStackError:
         stack level too deep
       Shared Example Group: :event_repository called from ./lib/ruby_event_store/spec/rom/event_repository_lint.rb:30
       Shared Example Group: :rom_event_repository called from ./spec/rom/adapters/memory/event_repository_spec.rb:9
       # ./lib/ruby_event_store/rom/adapters/memory/changesets/create_events.rb:7:in `commit'
       # ./lib/ruby_event_store/rom/adapters/memory/unit_of_work.rb:20:in `block in commit!'
       # ./lib/ruby_event_store/rom/adapters/memory/unit_of_work.rb:10:in `synchronize'
       # ./lib/ruby_event_store/rom/adapters/memory/unit_of_work.rb:10:in `commit!'
       # ./lib/ruby_event_store/rom/unit_of_work.rb:15:in `call'
       # ./lib/ruby_event_store/rom.rb:33:in `unit_of_work'
       # ./lib/ruby_event_store/rom/event_repository.rb:25:in `block in append_to_stream'
       # ./lib/ruby_event_store/rom.rb:45:in `handle_error'
       # ./lib/ruby_event_store/rom/event_repository.rb:24:in `append_to_stream'
       # /Users/anders/Projects/anderslemke/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:1142:in `block (3 levels) in <module:RubyEventStore>'
       # ./lib/ruby_event_store/spec/rom/event_repository_lint.rb:13:in `block (3 levels) in <module:ROM>'
       # ./lib/ruby_event_store/rom/memory.rb:49:in `run_lifecycle'
       # ./lib/ruby_event_store/spec/rom/event_repository_lint.rb:13:in `block (2 levels) in <module:ROM>'
       # /Users/anders/Projects/anderslemke/rails_event_store/lib/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'

Finished in 4.18 seconds (files took 0.81195 seconds to load)
203 examples, 130 failures, 7 pending
```
